
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: prod-

namespace: prod

resources:
  - ../../base

patches:
  - path: patch-deployment.yaml

images:
  - name: my-app
    newName: myregistry/my-app
    newTag: prod-latest
