apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namePrefix: dev-

# The modern way to handle common labels
labels:
  - pairs:
      env: development
      tier: frontend
    includeSelectors: true

images:
  - name: your-registry/kube-gitops-sample
    newTag: v1