apiVersion: v1
kind: Secret
metadata:
  name: my-app-secret
type: Opaque
stringData:
  # Kubernetes will Base64 encode these for you automatically
  DB_PASSWORD: "super-secret-password-123"
  API_KEY: "prod-api-key-998877"