
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: stage-

namespace: stage

resources:
  - ../../base

patches:
  - path: patch-deployment.yaml

images:
  - name: my-app
    newName: myregistry/my-app
    newTag: stage-latest
